version: '3.7'
services:
  kafka:
    image: bitnami/kafka:3.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: INTERNAL://:9093,CONTROLLER://:9094,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_NODE_ID: '1'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL

  kafka-create-topics:
    image: bitnami/kafka:3.7.0
    depends_on:
      - kafka
    command: >
      bash -c "
        /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server kafka:9093 --replication-factor 1 --partitions 1 --topic test-topic
      "

  influxdb:
    image: influxdb:2.7.6
    ports:
      - "8086:8086"

  kafka-lag-monitor:
    image: devatherock/kafka-lag-monitor:${DOCKER_TAG:-latest}
    depends_on:
      - influxdb
      - kafka-create-topics
    volumes:
      - ./src/integrationTest/resources/application-docker.yml:/config/application.yml
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: '-Xmx640m'
      MICRONAUT_CONFIG_FILES: '/config/application.yml'