micronaut:
  metrics:
    export:
      influx:
        step: 5s
        uri: http://influxdb:8086
kafka:
  clusters:
    - name: test-cluster
      servers: kafka:9093
  lag-monitor:
    initial-delay-seconds: 1
    interval-seconds: 10
    clusters:
      - name: test-cluster